theme: jekyll-theme-cayman
title :  Nate Sock Data Science Portfolio
description : Hi, I'm Nate Sock, a data scientist passionate about exploring and analyzing data to uncover insights and drive decision-making. With a background in [relevant field], I specialize in [specific areas of interest or expertise]. In my free time, I enjoy [hobbies or interests related to data science or other personal interests]. 

Feel free to explore my portfolio to see some of the projects I've worked on! 
